// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AerolineaAPI.Models;

public partial class AerolineaContext : DbContext
{
    public AerolineaContext(DbContextOptions<AerolineaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Aeropuertos> Aeropuertos { get; set; }

    public virtual DbSet<Aviones> Aviones { get; set; }

    public virtual DbSet<Pilotos> Pilotos { get; set; }

    public virtual DbSet<Rutas> Rutas { get; set; }

    public virtual DbSet<Vuelos> Vuelos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aeropuertos>(entity =>
        {
            entity.HasKey(e => e.ID_Aeropuerto).HasName("PK__Aeropuer__FC71A31DECCA391D");
        });

        modelBuilder.Entity<Aviones>(entity =>
        {
            entity.HasKey(e => e.ID_Avion).HasName("PK__Aviones__79F503782F1AA736");
        });

        modelBuilder.Entity<Pilotos>(entity =>
        {
            entity.HasKey(e => e.ID_Piloto).HasName("PK__Pilotos__99A850595A0F5CDC");
        });

        modelBuilder.Entity<Rutas>(entity =>
        {
            entity.HasKey(e => e.ID_Ruta).HasName("PK__Rutas__4851E68B1DBA3D6C");

            entity.HasOne(d => d.Destino).WithMany(p => p.RutasDestino).HasConstraintName("FK__Rutas__Destino_I__5070F446");

            entity.HasOne(d => d.Origen).WithMany(p => p.RutasOrigen).HasConstraintName("FK__Rutas__Origen_ID__4F7CD00D");
        });

        modelBuilder.Entity<Vuelos>(entity =>
        {
            entity.HasKey(e => e.ID_vuelo).HasName("PK__Vuelos__4D9069A941843E06");

            entity.HasOne(d => d.Avion).WithMany(p => p.Vuelos).HasConstraintName("FK__Vuelos__Avion_ID__5535A963");

            entity.HasOne(d => d.Piloto).WithMany(p => p.Vuelos).HasConstraintName("FK__Vuelos__Piloto_I__5441852A");

            entity.HasOne(d => d.Ruta).WithMany(p => p.Vuelos).HasConstraintName("FK__Vuelos__Ruta_ID__534D60F1");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}